#ifndef ____BVMMATHCODES_H__
#define __BVMMATHCODES_H__

enum eBvmMathCodes
{
	OP_MATH_POW		= 0,
	OP_MATH_SQR		= 1,
	OP_MATH_SQRT		= 2,
	OP_MATH_EXP		= 3,
	OP_MATH_SIN		= 4,
	OP_MATH_COS		= 5,
	OP_MATH_TAN		= 6,
	OP_MATH_ASIN		= 7,
	OP_MATH_ACOS		= 8,
	OP_MATH_ATAN		= 9,
	OP_MATH_ATAN2		= 10,
	OP_MATH_SINH		= 11,
	OP_MATH_COSH		= 12,
	OP_MATH_TANH		= 13,
	OP_MATH_HYPOT		= 14,
	OP_MATH_LN		= 15,
	OP_MATH_LOG10		= 16,
	OP_MATH_RND		= 17,
	OP_MATH_TRUNC		= 18,
	OP_MATH_FLOOR		= 19,
	OP_MATH_CEIL		= 20,
	OP_MATH_ISNAN		= 21,
	OP_MATH_ISINF		= 22,
};

#endif